using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Auto_Scre
{
    public partial class user_ManageData : DevExpress.XtraEditors.XtraUserControl
    {
        public user_ManageData()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            studentTableAdapter2.Fill(testDataSet2.student);
        }


    }
}
